name: Mirror to GitLab

on:
  push:
    branches:
      - '*'

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git push --prune https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_PASSWORD }}@gitlab.com/Rachelxcii/Rachelxcii.git +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
